// Generated by CoffeeScript 1.8.0
(function() {
  var CSON, basename, convert, converters, error, name, path, read, run, script, source, stdin, _, _ref;

  basename = require("path").basename;

  read = require("fairmont").read;

  CSON = require("./cson");

  _ref = process.argv, _ = _ref[0], script = _ref[1], path = _ref[2];

  name = basename(script);

  converters = {
    json2cson: function(source) {
      return CSON.stringify(JSON.parse(source));
    },
    cson2json: function(source) {
      return JSON.stringify(CSON.parse(source));
    }
  };

  convert = function(source) {
    return converters[name](source);
  };

  run = function(source) {
    return process.stdout.write(convert(source));
  };

  try {
    if (path != null) {
      run(read(path));
    } else {
      stdin = process.stdin;
      source = "";
      stdin.resume();
      stdin.on("data", function(data) {
        return source += data.toString("utf-8");
      });
      stdin.on("end", function() {
        return run(source);
      });
    }
  } catch (_error) {
    error = _error;
    console.error(error.message);
  }

}).call(this);
