// Generated by CoffeeScript 1.8.0
(function() {
  var parse, stringify, _ref;

  _ref = require("cson-safe"), parse = _ref.parse, stringify = _ref.stringify;

  module.exports = {
    parse: parse,
    stringify: stringify
  };

}).call(this);
